apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ServiceMonitorDetails
  namespace: bookinfo
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: details
  endpoints:
  - port: http
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ServiceMonitorRatings
  namespace: bookinfo
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: ratings
  endpoints:
  - port: http
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ServiceMonitorReviews
  namespace: bookinfo
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: reviews
  endpoints:
  - port: http
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ServiceMonitorProductpage
  namespace: bookinfo
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: productpage
  endpoints:
  - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: bookinfo
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: devops
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: bookinfo
spec:
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      team: devops
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
