apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometeus-gateway
  namespace: monitoring
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---    
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometeus
  namespace: monitoring
spec:
  hosts:
  - "*"
  gateways:
  - prometeus-gateway
  http:
  - match:
    - uri:
        exact: /prometheus
    route:
    - destination:
        host: prometheus-service
        port:
          number: 9090